import "%modules%/header/header";
import "%modules%/footer/footer";
import "%modules%/calculator/calculator";
import "%modules%/partners/partners";
import "%modules%/sliderhome/sliderhome";
import "%modules%/countries/countries";
import "%modules%/homehead/homehead";
import "%modules%/routes3/routes3";
import "%modules%/search/search";